In [2]:
import numpy as np

In [3]:
# Creating a numpy array from an already existing Python list
prices = [12,15,18,29]
prices_array = np.array(prices)

# Creating array out of strings
name = ['John', 'Matt', 'Rob']
name_array = np.array(name)

# Creating a multi-dimensional array
multi = [[1,2,3], [4,5,6]]
multi_array = np.array(multi)

In [4]:
# Check the dimensions of an array
multi_array.ndim

# check the data type of an array
multi_array.dtype

dtype('int32')

In [5]:
# Automated way of creating an array
auto_array = np.zeros(10)
auto_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
# defining data type while creating an array
arr = np.array([1,2,3,4], dtype=np.float64)
arr.dtype

dtype('float64')

In [10]:
# Convert array to an int data type
arr = arr.astype(np.int64)
arr.dtype

dtype('int64')

## Arithmetic Operations on Array

In [11]:
# Initialize two arrays
list_1 = [[23,23,12],[73,39,92]]
list_2 = [[25,53,23],[32,98,30]]

arr_1 = np.array(list_1)
arr_2 = np.array(list_2)


array([[25, 53, 23],
       [32, 98, 30]])

In [12]:
# Adding two arrays
arr_1 + arr_2

array([[ 48,  76,  35],
       [105, 137, 122]])

In [14]:
# Comparing two arrays
arr_1 > arr_2

array([[False, False, False],
       [ True, False,  True]])

## Indexing and Slicing Array

In [21]:
arr = np.array([[5,10,15,20],[100,200,300,400]])

for i in range(len(arr[1])):
    print(arr[1, i])

100
200
300
400


In [22]:
arr[0][1:5]

array([10, 15, 20])

In [26]:
# Slicing a multi-dimensional array
multi_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
multi_array
# Accessing a slice which contains 5,6,8,9
# Syntax
multi_array[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [27]:
multi_array[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [31]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr
#Let's say I want to access the corner elements like 1,3,8,9
arr[[0,0,2,2],[0,2,1,2]]


array([1, 3, 8, 9])

## Broadcasting

In [32]:
array_a = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_b = np.array([1,2,3])
print(array_a)
print(array_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]


In [33]:
#Now lets add them
array_a + array_b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])